# Copyright 2026 wee733
# SPDX-License-Identifier: Apache-2.0

schema_version: 1
publish: true
base_to_camera:
  parent_frame: base_link
  child_frame: camera_1_color_optical_frame
  translation: [0.65, -0.10, 0.85]
  rotation:
    [0.7809941368, 0.5891049807, -0.1248789722, -0.1655557979]
